# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "beta-2023-12-17"
components = [ "rust-src", "rustfmt", "clippy" ]
